# Generated by Django 2.2.10 on 2021-03-31 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500, verbose_name='Ответы')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Ответ текстом'), ('onew', 'Ответ с выбором одного варианта'), ('many', 'Ответ с выбором нескольких вариантов')], max_length=4, verbose_name='Тип ответа')),
                ('question_case', models.CharField(blank=True, max_length=500, verbose_name='Варианты ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название опроса')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('desc', models.CharField(max_length=300, verbose_name='Описание')),
                ('status', models.CharField(choices=[('notend', 'Не пройден'), ('ended', 'Пройден')], default='n', max_length=6, verbose_name='Статус')),
                ('questions', models.ManyToManyField(to='api.Question', verbose_name='Вопросы')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(blank=True, null=True, to='api.Answer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Survey', verbose_name='Тест'),
        ),
    ]
