# Generated by Django 2.2.10 on 2021-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='answers',
            field=models.ManyToManyField(blank=True, to='api.Answer'),
        ),
    ]
