# Generated by Django 2.2.10 on 2021-03-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_startedsurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartedSurvey',
        ),
    ]
