# Generated by Django 2.2.10 on 2021-03-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_survey_copied'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartedSurvey',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Survey')),
            ],
            bases=('api.survey',),
        ),
    ]
