# Generated by Django 2.2.10 on 2021-03-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_startedsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StartedSurvey', verbose_name='Тест'),
        ),
    ]
