# Generated by Django 2.2.10 on 2021-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210401_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateTimeField(editable=False, verbose_name='Дата начала'),
        ),
    ]
