# Generated by Django 2.2.10 on 2021-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210401_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
    ]
